sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t abhijitsinghas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhijitsinghas/docker-react npm run test